{% set version = "2.13.1" %}
{% set name = "pytensor" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/pymc-devs/pytensor.git
  git_rev: rel-2.13.1
  sha256: 2f704509abe811f9bca392b6848b1ed5b5011210fc19fd67d17e53f7f7362637

build:
  number: 0
  script:
    - python -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pytensor-cache = bin.pytensor_cache:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
    - numpy {{ numpy }}
    - versioneer 0.28
    - tomli
    - setuptools >=48.0.0
    # mkl-service is only available for linux-64, win-64, and osx-64.
    # For everything else, use openblas.
    - mkl {{ mkl }}            # [blas_impl == "mkl"]
    - openblas {{ openblas }}  # [blas_impl == 'openblas']
    # We also need the "blas" package. Otherwise we get reports
    # of "cblas.h: No such file or directory" at import time.
    # Ref: <https://github.com/conda-forge/aesara-feedstock/issues/80>
    - blas
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    - filelock
    - etuples
    - logical-unification
    - miniKanren
    - cons
    - typing_extensions
    - setuptools >=48.0.0

test:
  imports:
    - pytensor
    - pytensor.configdefaults
  requires:
    - pip
    - pytest
    - pre-commit
    - pytest-cov >=2.6.1
    - coverage >=5.1
    - pytest-benchmark
  source_files:
    - tests
  files:
    - check-for-warnings.py
    - allowed-warnings-base.txt
  commands:
    - pytensor-cache help
    - pip check
    - python check-for-warnings.py allowed-warnings-base.txt
    # TODO: enable these when figuring out how to fetch upstream GH repoe
    #- python -m pytest tests/test_*.py
    - python -m pytest tests/test_updates.py tests/test_breakpoint.py

about:
  home: https://github.com/pymc-devs/pytensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: An optimizing compiler for evaluating mathematical expressions.
  description: |
    PyTensor is a Python library that allows you to define, optimize/rewrite, and evaluate mathematical expressions
    involving multi-dimensional arrays efficiently.
  dev_url: https://github.com/pymc-devs/pytensor/
  doc_url: https://pytensor.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - aseyboldt
    - maresb
    - michaelosthege
    - twiecki
  skip-lints:
    - host_section_needs_exact_pinnings
    - python_build_tool_in_run