{% set name = "pytensor" %}
{% set version = "2.31.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/{{ name }}/archive/refs/tags/rel-{{ version }}.tar.gz
  sha256: 41b89de1c20adb04381c61b22527ddc11d401d83c276c050427a12676b5c4dbe
  patches:
    - 0001-patch-pyproject.toml.patch

build:
  number: 0
  script:
    - python -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pytensor-cache = pytensor.bin.pytensor_cache:main
  # upstream requirement
  skip: True  # [py<310 or py>=314]

requirements:
  build:
    - git  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - cython
    - pip
    - numpy {{ numpy }}
    # versioneer[toml]==0.29
    - versioneer 0.29
    - tomli
    - setuptools >=59.0.0
    - wheel
  run:
    - python
    - numpy >=1.17.0
    - scipy >=1,<2
    - filelock >=3.15
    - etuples
    - logical-unification
    - miniKanren
    - cons
    - setuptools >=59.0.0
    # necessary to compile code at runtime
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run_constrained:
    # rtd
    - sphinx >=5.1.0,<6
    # numba
    - numba >=0.57

test:
  imports:
    - pytensor
    - pytensor.breakpoint
    - pytensor.compile
    - pytensor.compile.builders
    - pytensor.compile.compiledir
    - pytensor.compile.compilelock
    - pytensor.compile.debugmode
    - pytensor.compile.function
    - pytensor.compile.function.pfunc
    - pytensor.compile.function.types
    - pytensor.compile.io
    - pytensor.compile.mode
    - pytensor.compile.monitormode
    - pytensor.compile.nanguardmode
    - pytensor.compile.ops
    - pytensor.compile.profiling
    - pytensor.compile.sharedvalue
    - pytensor.configdefaults
    - pytensor.configparser
    - pytensor.d3viz
    - pytensor.d3viz.d3viz
    - pytensor.d3viz.formatting
    - pytensor.gradient
    - pytensor.graph
    - pytensor.graph.basic
    - pytensor.graph.destroyhandler
    - pytensor.graph.features
    - pytensor.graph.fg
    - pytensor.graph.null_type
    - pytensor.graph.op
    - pytensor.graph.replace
    - pytensor.graph.rewriting
    - pytensor.graph.rewriting.basic
    - pytensor.graph.rewriting.db
    - pytensor.graph.rewriting.kanren
    - pytensor.graph.rewriting.unify
    - pytensor.graph.rewriting.utils
    - pytensor.graph.type
    - pytensor.graph.utils
    - pytensor.ifelse
    - pytensor.link.basic
    - pytensor.link.c
    - pytensor.link.c.basic
    - pytensor.link.c.cmodule
    - pytensor.link.c.exceptions
    - pytensor.link.c.interface
    - pytensor.link.c.op
    - pytensor.link.c.params_type
    - pytensor.link.c.type
    - pytensor.link.jax
    - pytensor.link.jax.dispatch
    - pytensor.link.jax.dispatch.basic
    - pytensor.link.jax.dispatch.blas
    - pytensor.link.jax.dispatch.blockwise
    - pytensor.link.jax.dispatch.einsum
    - pytensor.link.jax.dispatch.elemwise
    - pytensor.link.jax.dispatch.extra_ops
    - pytensor.link.jax.dispatch.math
    - pytensor.link.jax.dispatch.nlinalg
    - pytensor.link.jax.dispatch.pad
    - pytensor.link.jax.dispatch.random
    - pytensor.link.jax.dispatch.scalar
    - pytensor.link.jax.dispatch.scan
    - pytensor.link.jax.dispatch.shape
    - pytensor.link.jax.dispatch.signal
    - pytensor.link.jax.dispatch.signal.conv
    - pytensor.link.jax.dispatch.slinalg
    - pytensor.link.jax.dispatch.sort
    - pytensor.link.jax.dispatch.sparse
    - pytensor.link.jax.dispatch.subtensor
    - pytensor.link.jax.dispatch.tensor_basic
    - pytensor.link.jax.linker
    - pytensor.link.numba.dispatch
    - pytensor.link.numba.dispatch.basic
    - pytensor.link.numba.dispatch.blockwise
    - pytensor.link.numba.dispatch.cython_support
    - pytensor.link.numba.dispatch.elemwise
    - pytensor.link.numba.dispatch.extra_ops
    - pytensor.link.numba.dispatch.linalg._LAPACK
    - pytensor.link.numba.dispatch.linalg.decomposition.cholesky
    - pytensor.link.numba.dispatch.linalg.decomposition.lu
    - pytensor.link.numba.dispatch.linalg.decomposition.lu_factor
    - pytensor.link.numba.dispatch.linalg.solve.cholesky
    - pytensor.link.numba.dispatch.linalg.solve.general
    - pytensor.link.numba.dispatch.linalg.solve.lu_solve
    - pytensor.link.numba.dispatch.linalg.solve.norm
    - pytensor.link.numba.dispatch.linalg.solve.posdef
    - pytensor.link.numba.dispatch.linalg.solve.symmetric
    - pytensor.link.numba.dispatch.linalg.solve.triangular
    - pytensor.link.numba.dispatch.linalg.solve.tridiagonal
    - pytensor.link.numba.dispatch.linalg.solve.utils
    - pytensor.link.numba.dispatch.linalg.utils
    - pytensor.link.numba.dispatch.nlinalg
    - pytensor.link.numba.dispatch.random
    - pytensor.link.numba.dispatch.scalar
    - pytensor.link.numba.dispatch.scan
    - pytensor.link.numba.dispatch.signal
    - pytensor.link.numba.dispatch.signal.conv
    - pytensor.link.numba.dispatch.slinalg
    - pytensor.link.numba.dispatch.sparse
    - pytensor.link.numba.dispatch.subtensor
    - pytensor.link.numba.dispatch.tensor_basic
    - pytensor.link.numba.dispatch.vectorize_codegen
    - pytensor.link.numba.linker
    - pytensor.link.pytorch.dispatch
    - pytensor.link.pytorch.dispatch.basic
    - pytensor.link.pytorch.dispatch.blas
    - pytensor.link.pytorch.dispatch.blockwise
    - pytensor.link.pytorch.dispatch.elemwise
    - pytensor.link.pytorch.dispatch.extra_ops
    - pytensor.link.pytorch.dispatch.math
    - pytensor.link.pytorch.dispatch.nlinalg
    - pytensor.link.pytorch.dispatch.scalar
    - pytensor.link.pytorch.dispatch.shape
    - pytensor.link.pytorch.dispatch.sort
    - pytensor.link.pytorch.dispatch.subtensor
    - pytensor.link.pytorch.linker
    - pytensor.link.utils
    - pytensor.link.vm
    - pytensor.misc.frozendict
    - pytensor.misc.may_share_memory
    - pytensor.misc.ordered_set
    - pytensor.misc.pkl_utils
    - pytensor.npy_2_compat
    - pytensor.printing
    - pytensor.raise_op
    - pytensor.scalar
    - pytensor.scalar.basic
    - pytensor.scalar.loop
    - pytensor.scalar.math
    - pytensor.scalar.sharedvar
    - pytensor.scan
    - pytensor.scan.basic
    - pytensor.scan.checkpoints
    - pytensor.scan.op
    - pytensor.scan.rewriting
    - pytensor.scan.scan_perform
    - pytensor.scan.utils
    - pytensor.scan.views
    - pytensor.sparse
    - pytensor.sparse.basic
    - pytensor.sparse.rewriting
    - pytensor.sparse.sandbox
    - pytensor.sparse.sandbox.sp2
    - pytensor.sparse.sharedvar
    - pytensor.sparse.type
    - pytensor.sparse.utils
    - pytensor.tensor
    - pytensor.tensor._linalg
    - pytensor.tensor._linalg.solve
    - pytensor.tensor._linalg.solve.rewriting
    - pytensor.tensor.basic
    - pytensor.tensor.blas
    - pytensor.tensor.blas_c
    - pytensor.tensor.blas_headers
    - pytensor.tensor.blas_scipy
    - pytensor.tensor.blockwise
    - pytensor.tensor.conv
    - pytensor.tensor.conv.abstract_conv
    - pytensor.tensor.einsum
    - pytensor.tensor.elemwise
    - pytensor.tensor.exceptions
    - pytensor.tensor.extra_ops
    - pytensor.tensor.fourier
    - pytensor.tensor.functional
    - pytensor.tensor.inplace
    - pytensor.tensor.interpolate
    - pytensor.tensor.io
    - pytensor.tensor.linalg
    - pytensor.tensor.math
    - pytensor.tensor.nlinalg
    - pytensor.tensor.pad
    - pytensor.tensor.random
    - pytensor.tensor.random.basic
    - pytensor.tensor.random.op
    - pytensor.tensor.random.rewriting
    - pytensor.tensor.random.rewriting.basic
    - pytensor.tensor.random.rewriting.jax
    - pytensor.tensor.random.rewriting.numba
    - pytensor.tensor.random.type
    - pytensor.tensor.random.utils
    - pytensor.tensor.random.var
    - pytensor.tensor.rewriting
    - pytensor.tensor.rewriting.basic
    - pytensor.tensor.rewriting.blas
    - pytensor.tensor.rewriting.blas_c
    - pytensor.tensor.rewriting.blas_scipy
    - pytensor.tensor.rewriting.blockwise
    - pytensor.tensor.rewriting.conv
    - pytensor.tensor.rewriting.einsum
    - pytensor.tensor.rewriting.elemwise
    - pytensor.tensor.rewriting.extra_ops
    - pytensor.tensor.rewriting.jax
    - pytensor.tensor.rewriting.linalg
    - pytensor.tensor.rewriting.math
    - pytensor.tensor.rewriting.numba
    - pytensor.tensor.rewriting.ofg
    - pytensor.tensor.rewriting.shape
    - pytensor.tensor.rewriting.special
    - pytensor.tensor.rewriting.subtensor
    - pytensor.tensor.rewriting.subtensor_lift
    - pytensor.tensor.rewriting.uncanonicalize
    - pytensor.tensor.shape
    - pytensor.tensor.sharedvar
    - pytensor.tensor.signal
    - pytensor.tensor.signal.conv
    - pytensor.tensor.slinalg
    - pytensor.tensor.sort
    - pytensor.tensor.special
    - pytensor.tensor.subtensor
    - pytensor.tensor.type
    - pytensor.tensor.type_other
    - pytensor.tensor.utils
    - pytensor.tensor.variable
    - pytensor.tensor.xlogx
    - pytensor.typed_list
    - pytensor.typed_list.basic
    - pytensor.typed_list.type
    - pytensor.updates
    - pytensor.utils
  requires:
    - pip
    - pytest
    - pre-commit
    - jax
    - numba
    - pytorch
  source_files:
    - tests
  files:
    - check-for-warnings.py
    - allowed-warnings-base.txt
  commands:
    - pip check
    - pytensor-cache help
    - python check-for-warnings.py allowed-warnings-base.txt
    # this flag prevents a known issue with macOS clang++ throwing errors when narrowing types in implicit casts
    - export PYTENSOR_FLAGS="gcc__cxxflags=-Wno-c++11-narrowing"  # [osx]
    - python -m pytest tests/test_breakpoint.py tests/test_config.py tests/test_gradient.py tests/test_ifelse.py tests/test_raise_op.py tests/test_rop.py tests/test_updates.py

about:
  home: https://github.com/pymc-devs/pytensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: doc/LICENSE.txt
  summary: An optimizing compiler for evaluating mathematical expressions.
  description: |
    PyTensor is a Python library that allows you to define, optimize/rewrite, and evaluate mathematical expressions
    involving multi-dimensional arrays efficiently.
  dev_url: https://github.com/pymc-devs/pytensor
  doc_url: https://pytensor.readthedocs.io

extra:
  recipe-maintainers:
    - aseyboldt
    - maresb
    - michaelosthege
    - twiecki
  skip-lints:
    - host_section_needs_exact_pinnings
    - python_build_tool_in_run
    - compilers_must_be_in_build