{% set version = "2.23.0" %}
{% set name = "pytensor" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/{{ name }}/archive/refs/tags/rel-{{ version }}.tar.gz
  sha256: 543eebd466db93190ac454c5a633948f724a64021e4fe39d89344e7423a5798b

build:
  number: 1
  script:
    - python -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pytensor-cache = pytensor.bin.pytensor_cache:main
  skip: True #  [py<=310]

requirements:
  build:
    - git  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
    - numpy {{ numpy }}
    - versioneer 0.28
    - tomli
    - setuptools >=48.0.0
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    - filelock
    - etuples
    - logical-unification
    - miniKanren
    - cons
    - typing_extensions
    - setuptools >=48.0.0
    # necessary to compile code at runtime
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  imports:
    - pytensor
    - pytensor.configdefaults
  requires:
    - pip
    - pytest
    - pre-commit
  source_files:
    - tests
  files:
    - check-for-warnings.py
    - allowed-warnings-base.txt
  commands:
    - pip check
    - pytensor-cache help
    - python check-for-warnings.py allowed-warnings-base.txt
    # this flag prevents a known issue with macOS clang++ throwing errors when narrowing types in implicit casts
    - export PYTENSOR_FLAGS="gcc__cxxflags=-Wno-c++11-narrowing"  # [osx]
    # skipping test_config_pickling because of a regex error which seems to be related to pickle
    # AssertionError: Regex pattern did not match. Regex: "Can't pickle local object"
    # Input: "Can't get local object 'test_config_pickling.<locals>.<lambda>'" 
    - python -m pytest -k "not test_config_pickling" tests/test_breakpoint.py tests/test_config.py tests/test_gradient.py tests/test_ifelse.py tests/test_raise_op.py tests/test_rop.py tests/test_updates.py
    - python -m pytest tests/test_printing.py  # [osx]

about:
  home: https://github.com/pymc-devs/pytensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: doc/LICENSE.txt
  summary: An optimizing compiler for evaluating mathematical expressions.
  description: |
    PyTensor is a Python library that allows you to define, optimize/rewrite, and evaluate mathematical expressions
    involving multi-dimensional arrays efficiently.
  dev_url: https://github.com/pymc-devs/pytensor/
  doc_url: https://pytensor.readthedocs.io

extra:
  recipe-maintainers:
    - aseyboldt
    - maresb
    - michaelosthege
    - twiecki
  skip-lints:
    - host_section_needs_exact_pinnings
    - python_build_tool_in_run
